services: 
  catservice: 
    container_name: ts-catservice-docker
    restart: always
    ports: 
      - 3001:${PORT}
    env_file:
      - .env
    build: 
      context: .
      target: production
      args: 
        - PORT=${PORT}
    volumes: 
      - volume:/usr/src/app
      - ignore:/usr/src/app/node_modules/
volumes: 
  ignore:
  volume:
    